### ISSUE TITLE
Category setting for availability is hidden

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#23]
Video of issue: https://i.imgur.com/IPxAObY.mp4

**Comment by alecritson** [comment]
This should be resolved in version `0.11.2` of the `@getcandy` modules.

**Comment by Repox** [comment]
No, that issue persists.
But I can no longer see categories in the table view, but tree view now works 😁

**Comment by alecritson** [comment]
Just to confirm, it doesn't look like this for you:

![image](https://user-images.githubusercontent.com/1488016/104458171-e92c7580-55a2-11eb-9502-d6ff4b4a9be7.png)

**Comment by Repox** [comment]
No, my view looks like this:

![Skærmbillede 2021-01-13 kl  14 27 30](https://user-images.githubusercontent.com/673280/104458379-97d4b400-55ab-11eb-9a26-dd1480b0b8c9.png)

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
